#!/bin/bash
#SBATCH -J gaussian
#SBATCH --array=0-3
#SBATCH -p standard-mem-s
#SBATCH --mem=60GB
#SBATCH -c 8

module purge
module load gaussian/g16a

input_name=dihe_${SLURM_ARRAY_TASK_ID}.neg              # change as needed
input_file=${input_name}.gjf
output_file=${input_name}.log

mkdir ${input_name}
cp gaussIn/${input_file} ${input_name}/.
cd ${input_name}
g16 < ${input_file} > ${output_file}
